### ISSUE TITLE
Flac song stops and restart

### ISSUE THREAD

**Issue by dorel14** [airsonic-advanced/airsonic-advanced#118]
Hello 

## Problem description
When i listen for flac files , it regurlalrly stops and restart afeter few seconds
I can see this error in console

`Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH`

### Steps to reproduce

just listen for flac files 

## System information

 * **Airsonic version**: 10.6.0-SNAPSHOT.20200302045745**
 * **Operating system**: *Debian 10.

 * **Java version**: *java 11.0.5.*
 * **Proxy server**: *NGINX 
 * **Client**: *Chrome.*
 * **Language**: *French*

## Additional notes

No Transcoding set up for flac

*Include any extra notes here. Otherwise you may remove this section.*

**Comment by randomnicode** [comment]
I'm unable to reproduce this issue. FLACs work fine for my servers. There are integration tests that test FLAC streaming also, and they pass too.

This sounds like an nginx issue. What might help isolate the issue is if you could post:
- the request headers of the request that was sent from your Chrome
- the response headers of the request that throws the error from your Chrome
- the actual size of the file (in bytes)

The first two, you should be able to find in your Network tab in Chrome Dev Tools.
The latter you should be able to `ls` for.

Here is a sample stack overflow issue on the matter: https://stackoverflow.com/questions/25993826/err-content-length-mismatch-on-nginx-and-proxy-on-chrome-when-loading-large-file

**Comment by dorel14** [comment]
Hello 
Thx the solution was in stackoverflow 
I've set up this in my nginx conf , and it's now OK

proxy_buffering off;
