### ISSUE TITLE
example: nginx local block configuration using websockets for airsonic-advanced

### ISSUE THREAD

**Issue by jobenvil** [airsonic-advanced/airsonic-advanced#145]
This is related to the websockets closed [issue](https://github.com/airsonic-advanced/airsonic-advanced/issues/125). 

Since I had the same issue and I came up configuring nginx in the following way:

```     
        ###
        # airsonic-advanced
        ###

    location /airsonic {
        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        "Upgrade";
        proxy_http_version 1.1;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Host  $http_host;
        proxy_set_header Host              $http_host;
        proxy_max_temp_file_size           0;
        proxy_pass                         http://192.168.178.90:8070;
        proxy_redirect                     http:// https://;
        proxy_buffering off;
        proxy_request_buffering off;


        client_max_body_size 0;

        access_log      /var/log/nginx/airsonic_access.log;
        error_log       /var/log/nginx/airsonic_error.log;
       #access_log      off;
    }

```

This config give the best output results and no warning or errors on chrome inspect console.

remarks: airsonic-advanced is not running on the same nginx server. airsonic-advanced running on `192.168.178.90:8070 `

Maybe could be from any help to others ussing the websockets used by airsonic advanced.

**Comment by randomnicode** [comment]
👍 We should probably add this somewhere to some documentation.

**Comment by jobenvil** [comment]
feel free to add anywhere and close the issue at your convenience. Thanks for your work!

**Comment by jobenvil** [comment]
It makes no sense to let the issue open, since googling should help to find the topic. The name of the topic has enough information to be found out (IMO). Sorry I didn't do sooner.

**Comment by BobWs** [comment]
For me it isn't working the reverse proxy setup. I have install this image on docker Synology and setup the reverse proxy via the GUI of synology but it isn't working when trying to login I'm redirected to my Synology DSM page instead of the Airsonic. When browsing to `https://airsonic.mydomain.com/login` I see the Airsonic (SSL) login page but after I put in my credentials I'm redirect to the main DSM page.

Any idea how to solve this?

![Screen_Shot](https://user-images.githubusercontent.com/5485820/80913536-8ca36600-8d45-11ea-90a4-edb7fe3c0ec3.png)

**Comment by jobenvil** [comment]
@BobWs generally speaking is not a good idea to reopen issues that already were closed. You use Synology and a subdomain, that was not my case. 

You could open a new issue and filling the template to describe better your issue. It's a kindly suggestion.

**Comment by randomnicode** [comment]
With the new changes in 01/2021, the following line in the config may also help:
```
proxy_set_header Origin            '';
```

**Comment by jobenvil** [comment]
I edited the nginx local block configuration accordingly.

**Comment by randomnicode** [comment]
Following https://github.com/airsonic-advanced/airsonic-advanced/pull/467,

this line isn't needed anymore:
```
 proxy_set_header Origin            '';
```

**Comment by edenist** [comment]
For those who are using apache as their reverse proxy, here is my config to pass http + ws traffic through to my airsonic server running under tomcat9.
You need to have `mod_proxy`, `mod_proxy_http` and `mod_proxy_wstunnel` enabled in your apache configuration. 

```
  #############################
  ### airsonic proxy      ###
  #############################

  ProxyPass /sonic/ http://sonic:8080/sonic/
  ProxyPassReverse /sonic/ http://sonic:8080/sonic/

  #websocket proxying
  RewriteEngine on
  RewriteCond %{HTTP:Upgrade} websocket [NC]
  RewriteCond %{HTTP:Connection} upgrade [NC]
  RewriteRule ^/?(.*) "ws://sonic:8080/$1" [P,L]

```

Note that I have 'sonic' configured in my hosts file, so replace http://sonic and ws://sonic with the IP address or hostname of your own airsonic server.

**Comment by udf** [comment]
You should avoid using `$http_host` and use `$host` instead, see this link for more info: https://github.com/yandex/gixy/blob/master/docs/en/plugins/hostspoofing.md

**Comment by jobenvil** [comment]
@udf Very appreciated your suggestion. I changed both directives.

**Comment by edenist** [comment]
@schniepp I'm running HTTPS, but only on the external side of my proxy. Internally it is just using HTTP hence the rule only refers to http. By the sound of things that isn't necessarily the issue for you, but it is an issue which pops up with reverse proxies. 
I would recommend also setting `ProxyPreserveHost On` in your apache config, which makes sure the full host from the header is passed through, otherwise the libresonic server only sees the host in the proxy file [and thus won't know the full base URL when it sends a redirect to login etc].

**Comment by schniepp** [comment]
@edenist : unfortunately, the `ProxyPreserveHost On` did not resolve the issue. As a matter of fact, nothing changed. 

May I ask why you used this:
`RewriteRule ^/?(.*) "ws://sonic:8080/$1" [P,L]`
As opposed to this: 
`RewriteRule ^sonic/?(.*) "ws://sonic:8080/sonic/$1" [P,L]`

If I run HTTPS, would I have to do this: 
`RewriteCond %{HTTP:Upgrade} websocket [NC]`
Instead of this:
`RewriteCond %{HTTPS:Upgrade} websocket [NC]`

**Comment by awsms** [comment]
> @edenist : thanks so much for posting the apache settings! I can't seem to get it to work in my case.
> 
> Are you running HTTP or HTTPS? When I go to `https://myhost.com/sonic`, it forwards to `https://myhost.com/login`, when I believe it should be `https://myhost.com/sonic/login`, and I can't seem to find why.

i've been having this same issue for months now. did you find a way?

**Comment by IMHLAR** [comment]
> > @edenist : thanks so much for posting the apache settings! I can't seem to get it to work in my case.
> > Are you running HTTP or HTTPS? When I go to `https://myhost.com/sonic`, it forwards to `https://myhost.com/login`, when I believe it should be `https://myhost.com/sonic/login`, and I can't seem to find why.
> 
> i've been having this same issue for months now. did you find a way?

I had the same issue and was finally able to solve it by editing my airsonic.service file (/etc/systemd/system/airsonic.service on Fedora) and changing the line "-Dserver.context-path=/airsonic " to "-Dserver.servlet.context-path=/airsonic" as suggested here: https://www.reddit.com/r/airsonic/comments/g9oao5/airsonic_advanced_url_not_working/

**Comment by jobenvil** [comment]
> I had the same issue and was finally able to solve it by editing my airsonic.service file (/etc/systemd/system/airsonic.service on Fedora) and changing the line "-Dserver.context-path=/airsonic " to "-Dserver.servlet.context-path=/airsonic" as suggested here: https://www.reddit.com/r/airsonic/comments/g9oao5/airsonic_advanced_url_not_working/

Indeed, that was my first problem setting up airsonic advanced. This was handled here:  https://github.com/airsonic-advanced/airsonic-advanced/issues/88#issuecomment-588423532

**Comment by schniepp** [comment]
@IMHLAR : OMG, that did it for me, too!!! Thank you so much for taking the time to follow up. You made my day!!!
