### ISSUE TITLE
Docker airsonic advanced feature request

### ISSUE THREAD

**Issue by g2ufo** [airsonic-advanced/airsonic-advanced#157]
Please add PUID and PGID in docker like linuxserver/airsonic

**Comment by randomnicode** [comment]
Hmm, I think that's the linuxserver.io team.

Does docker's `--user` param not work?

Linuxserver.io on their notes for puid/pgid have some mention of the `--user` parameter

**Comment by Adrian-Rasmussen** [comment]
The `--user` parameter appears to change the user inside the docker container itself, rather than mapping to an existing host user. Doing this makes the docker unable to launch:
`mkdir: can't create directory '/var/airsonic/transcode': Permission denied`

Here is where linuxserver makes use of the `PUID`/`PGID` values - https://github.com/linuxserver/docker-baseimage-ubuntu/blob/bionic/root/etc/cont-init.d/10-adduser

**Comment by pwatk** [comment]
The Synology frontend doesn't allow you to set the --user parameter so I would also appreciate this change.

**Comment by randomnicode** [comment]
Please test?

**Comment by pwatk** [comment]
First run works fine but if I restart the container it fails to start and I see this in the log.
```
Docker USER id: 0
Docker PUID env: 1036
Docker USER group: 0
Docker PGID env: 100
useradd: user 'au' already exists
```

**Comment by randomnicode** [comment]
> First run works fine but if I restart the container it fails to start and I see this in the log.

Sounds like you're reusing the same container. Changes need to be made to account for a nonthrowaway persistent container scenario.

**Comment by randomnicode** [comment]
Okay, try with the next snapshot

**Comment by pwatk** [comment]
This issue is now resolved. Thank you.

**Comment by znedw** [comment]
This is working perfect for me, thank-you!
If you're getting:
`mkdir: can't create directory '/var/airsonic/transcode': Permission denied`
Just stop the container and rm -rf the transcode folder

**Comment by randomnicode** [comment]
closing this now
