### ISSUE TITLE
Stable Release 10.6.0

### ISSUE THREAD

**Issue by randomnicode** [airsonic-advanced/airsonic-advanced#183]
There seem to be enough changes and stability now to merit a stable release.

Thereafter we can move to 11.0 snapshots and merge breaking changes to upgrade old stuff to modern counterparts.

If there are no outstanding bugs/issues in the next few days for the current prerelease, it'll get promoted to stable.

**Comment by randomnicode** [comment]
Last call for issues stopping stable release.

Next release WILL be breaking and NON-backwards-compatible!!

**Comment by chrstn-hntschl** [comment]
When trying to switch from vanilla airsonic to this implementation I realized that the mobile app I am currently using (DSub, https://github.com/daneren2005/Subsonic) fails to connect to the server, most likely due to the changes in credentials management. Are you aware of mobile applications (android) that work with airsonic-advanced?
