### ISSUE TITLE
Milliseconds displayed in track length 

### ISSUE THREAD

**Issue by dalecooper** [airsonic-advanced/airsonic-advanced#208]
## Problem description

In the queue some tune lengths are shown with milliseconds.
See screenshot below :

![Screenshot_20200417_145612](https://user-images.githubusercontent.com/16813929/79571975-71392980-80bc-11ea-88de-f95725bf6a85.png)

I play only FLACs. This doesn't happen with all albums, so I guess this is simply how metadata are saved in my files.
Not sure if this is a bug or a feature, but I find it a bit confusing. Any chance to avoid that much details ?

### Steps to reproduce

1. Add some tunes to the queue

## System information

 * **Airsonic version**: 10.6.0-SNAPSHOT.20200417044128 (same with previous versions)
 * **Operating system**: Armbian Buster
 * **Java version**: Openjdk 8
 * **Proxy server**: Nginx
 * **Client**: Firefox / Ubuntu
 * **Language**: EN

**Comment by Faeb35** [comment]
Its the same in my Airsonic Advanced. I only have MP3 files.
For me it seems to be related to files with variable bitrate:
![grafik](https://user-images.githubusercontent.com/9485516/79582351-f0822980-80cb-11ea-8b54-2a0ec9d0bdba.png)

**Comment by randomnicode** [comment]
No, actually, this is a direct consequence of https://github.com/airsonic-advanced/airsonic-advanced/pull/54 which stores and uses more precise durations internally (for all files, not just vbr). Base airsonic is not as precise internally, and as a consequence the errors can add up. A minor example is a playlist with track lengths of 10.4 and 10.4 seconds, which should round up to 21 seconds (20.8), but since airsonic does not keep subsecond precision, it shows up as only 20 seconds. This is just an example with 2 tracks, but the error can get much larger. It additionally has consequences when generating content-length headers for transcoded files where the content length is inaccurately determined because we've lost the subsecond precision (it can be and usually is corrected in other ways by adding a padding at the end, but still bears consequence) .

As the PR notes, we can play around with the display some more now that the internal precision is high. We should probably just show the second-level precision for display purposes.

**Comment by randomnicode** [comment]
@dalecooper This should be resolved in #213 now (minus the captions on the playlist)

**Comment by dalecooper** [comment]
@randomnicode just updated to latest release and I have a new issue : whenever I add a full album to the queue, it starts playing as usual and I can go next / previous track but the queue remains empty.
Also, when I click on a album to show its page, all I can see is the artwork but nothing else, no artist, no title, no track. It only says "Processing..." and "No data available in table"
So for now I can't confirm your fix works.
Let me know if you want me to file a new issue.

**Comment by randomnicode** [comment]
@dalecooper yes please, though unable to reproduce this issue. Sounds like a JS issue, which indicates an issue with your specific browser. Check your browser console for any exceptions?

**Comment by randomnicode** [comment]
@dalecooper may I please close this issue if it is resolved?

**Comment by dalecooper** [comment]
Yes, can confirm it's OK, thank you for the really fast fix. I'll close the issue myself.
As for the other issue I'm still trying to figure out what's wrong since it doesn't happen everytime, will open an new issue if needed.
