### ISSUE TITLE
Standalone with external database (mariadb) help needed

### ISSUE THREAD

**Issue by count00zero** [airsonic-advanced/airsonic-advanced#231]
Hi there!

I am trying to run airsonic-advanced standalone with an external database (mariadb) and the correct "driver" ... mariadb-java-client-2.6.0.jar
Running with the local database everything runs great!
Running within tomcat9 (I have to admit; there I am running the "classical" version of airsonic) it also works with the external MariaDB while using mariadb-java-client-2.6.0.jar..

But I cant' get it running standalone using mariaDB ...

Amy help is highly appreciated :)

` Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'themeSource': Unsatisfied dependency expressed through method 'setSettingsService' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'settingsService': Unsatisfied dependency expressed through field 'internetRadioDao'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'internetRadioDao': Unsatisfied dependency expressed through field 'daoHelper'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'daoHelper': Unsatisfied dependency expressed through field 'jdbcTemplate'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/airsonic/player/spring/DatabaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.ValidationFailedException: `

**Comment by randomnicode** [comment]
Don't think you need any drivers. The drivers are built in to the standalone jars.

You need to post the full stacktrace. This is incomplete and not enough to go off of.

Have you set the appropriate vars to redirect the jars to the right db in your airsonic.properties?

**Comment by count00zero** [comment]
OK.
I start it that way: /usr/bin/java -Dairsonic.home=/var/airsonic-advanced -Dserver.port=8070 -Dserver.context-path=/airsonic -DUPNP_PORT=4042 -jar /var/airsonic-advanced/airsonic.war

DB-related content of the .properties file:
DatabaseConfigType=embed
DatabaseConfigEmbedDriver=org.mariadb.jdbc.Driver
DatabaseConfigEmbedUrl=jdbc:mariadb://localhost:3306/airsonicadvanced
DatabaseConfigEmbedPassword=airsonic
DatabaseConfigEmbedUsername=airsonic

I will upload the log in a few seconds

**Comment by count00zero** [comment]
[aa.log](https://github.com/airsonic-advanced/airsonic-advanced/files/4511604/aa.log)

**Comment by randomnicode** [comment]
So, a few things:

> I start it that way: /usr/bin/java -Dairsonic.home=/var/airsonic-advanced -Dserver.port=8070 -Dserver.context-path=/airsonic -DUPNP_PORT=4042 -jar /var/airsonic-advanced/airsonic.war

This invocation is slightly incorrect.
`-Dserver.context-path` should be `-Dserver.servlet.context-path`
`-DUPNP_PORT` should be `-DUPnpPort`

Second, from the logs, the external DB looks polluted. There's already tables and data in your db and something already created (at least part of) the database. The migrations are failing because the existing migrations sitting in the database are different from what's trying to run. Did you run things with airsonic in the same database first?

**Comment by count00zero** [comment]
1st: thanks a lot for the corrections!
2nd: yeah, I copied my previous airsonic DB over to the new one.
Du you mean, I've to empty the database and cannot use the old imported data?

**Comment by randomnicode** [comment]
You can.

The issue is that airsonic uses a higher mysql vachar limit (512), which causes them issues for utf8 collations in mysql and mariadb.
airsonic-advanced uses a lower default limit (384).

Since you're not setting it in your properties file, the defaults are being used and there is a mismatch.
The DB was migrated initially using airsonic and thus has many tables with varchar(512). Then you try running airsonic-advanced on the same tables and while verifying tables it runs into the issue that it wants to see varchar(384) for some columns, but instead sees varchar(512).

You also haven't specified what version of MariaDB (or collation) you are using because that affects what the default max width for each table column is before you start running into problems, thus it's hard to gauge what your max varchar size is supposed to be.

You have three options:
- You can try setting your `DatabaseMysqlMaxlength` to 512 in your properties file (or on the command line) when starting up airsonic-advanced. Your old (existing) migrations will check out fine, but the newer migrations might fail if your DB can't handle the expanded column size.
- You can just start anew. The media files will scan again.
- You can wait for #234 to merge which will ignore the mismatch in varchar columns

**Comment by randomnicode** [comment]
@count00zero Okay try the new snapshot version to see if your issues are resolved

**Comment by count00zero** [comment]
Hi again and THANK YOU very much!!
The new snapshot works like a charm!!!

Great work!!
