### ISSUE TITLE
Airsonic service won't start

### ISSUE THREAD

**Issue by SyntrophicConsortium** [airsonic-advanced/airsonic-advanced#250]
I had issues with some of the newer snapshots not working, the webserver and player application never start (but the service does). The log always ended with the DLNA server shutting down, and nothing after that (and no fatal exceptions). 

Anyway, with the latest version 11.0.0-SNAPSHOT.20200425031103, the airsonic service is now failing to start with an exit code 1. 

systemctl status airsonic:

```
 Apr 25 10:24:16 Fractal systemd[1]: airsonic.service: User lookup succeeded: uid=970 gid=970
 Apr 25 10:24:16 Fractal systemd[1391419]: airsonic.service: Executing: /usr/bin/java -Xmx700m -Dairsonic.home=/var/airsonic -Dserver.context-path=/airsonic -Dserver.port=8080 -D>
 Apr 25 10:24:17 Fractal systemd[1]: airsonic.service: Failed to read oom_kill field of memory.events cgroup attribute: No such file or directory
 Apr 25 10:24:17 Fractal systemd[1]: airsonic.service: Child 1391419 belongs to airsonic.service.
 Apr 25 10:24:17 Fractal systemd[1]: airsonic.service: Main process exited, code=exited, status=1/FAILURE
 Apr 25 10:24:17 Fractal systemd[1]: airsonic.service: Failed with result 'exit-code'.
 Apr 25 10:24:17 Fractal systemd[1]: airsonic.service: Service will not restart (restart setting)
 Apr 25 10:24:17 Fractal systemd[1]: airsonic.service: Changed running -> failed
 Apr 25 10:24:17 Fractal systemd[1]: airsonic.service: Unit entered failed state.
 Apr 25 10:24:17 Fractal systemd[1]: airsonic.service: Control group is empty.
```

That looks possibly specific to my machine, but I'm unable to reboot currently. It will have to wait until rdiff-backup is finished running later today.

**Comment by SyntrophicConsortium** [comment]
I found the problem in this case by running airsonic directly from the commandline. I got an error that "this version of the Java Runtime only recognizes class file versions up to 54.0". I had to install openjdk11 to get Airsonic to start.

It still throws a whole bunch of exceptions about missing mp3s though, and the webserver and media services never start. I'm going to close this particular issue.

**Comment by SyntrophicConsortium** [comment]
I didn't mean to close, as although the service does start, it exits.

**Comment by randomnicode** [comment]
If this issue is regarding the minimum requirements for 11.x series, then this is documented already on the front page. You need at least Java 11 (you can also download a higher version, but that is the minimum).

From the README.md:

> You need a minimum Java Runtime Environment (JRE) of 1.8 for 10.6.x series and 11 for 11.x onwards (including snapshots). It is run similarly to (and in lieu of) vanilla Airsonic.

Java 11 is the current LTS release for Java, vanilla Airsonic has been using an old Java release (1.8), but it too is scheduled to change soon, so you will encounter the same issues there also soon unless you upgrade.

As far as class errors, perhaps you haven't set up your JRE correctly? Wherever you installed your Java, perhaps the path is still picking up 1.8 or something like that?

The JRE version cannot be an issue because aside from users, we have automated testing that occurs on all java versions after and including 11, and they all seem to pass (they would have thrown exceptions if the release was unable to run against a particular JRE)

**Comment by randomnicode** [comment]
If you'd like to stay on an older jdk, then maybe you can try this snapshot: https://github.com/airsonic-advanced/airsonic-advanced/releases/tag/11.0.0-SNAPSHOT.20200425020959

This was the last release prior to the java 11 switch.
Keep in mind your db if you've used the latest snapshot, it is incompatible with earlier versions, so you need to restore the backup it made (which sits alongside wherever your current db folder is).

**Comment by SyntrophicConsortium** [comment]
I apologize for missing that. I will look into it and see what I can find as far my Java configuration goes.

Sent from ProtonMail mobile

-------- Original Message --------
