### ISSUE TITLE
Sonos Support

### ISSUE THREAD

**Issue by sandersantema** [airsonic-advanced/airsonic-advanced#299]
Is Sonos supported by airsonic-advanced? And if so what's the correct way to set this up?

**Comment by randomnicode** [comment]
Yeah, both `airsonic` and `airsonic-advanced` share the same Sonos support, and not sure it's currently in a decent state. There should be a dedicated tab in Settings for Sonos if you'd like to try it.

There _is_ a PR in the works https://github.com/airsonic/airsonic/pull/1356 to make the support better. Might take a look at and merge into airsonoic-advanced soon.

**Comment by sandersantema** [comment]
I've tried it for a bit tweaking configurations but I can't seem to get it to work. Setup using an anonymous user (without username and password) doesn't allow me to see any files and setup with user credentials fails at login. I suspect that that PR might solve this.

**Comment by randomnicode** [comment]
Yeah, will take a look at it. The auth stuff in that pr looks a bit all over the place.

**Comment by randomnicode** [comment]
@sandersantema should merge sonos stuff in a bit

**Comment by sandersantema** [comment]
It works perfectly now! Thanks a lot.

**Comment by sandersantema** [comment]
There might be one little bug, I wasn't able to browse trough my music as an anonymous user, I suppose this is either a bug or a result of the improved security. With multi user it does work, but it might be good to mention it doesn't using one anonymous user.

**Comment by ydmk** [comment]
It's not a bug, it's a deliberate security feature.

An anonymous use is not able to browse through music because they shouldn't by definition have any permissions: they're anonymous; they're unverified, unknown, untrusted. If they have access to everything, then there's no point of security. They should only have access to things that are public (and therefore have been explicitly made available to everyone, including anonymous).

Thus, they are able to browse _public_ stuff (like, for instance, if you make your playlist *public*, they should be able to see it), but have no rights to see non-public stuff.

If you'd like to be able to browse all your non-public music, either use one of your existing accounts or create a new user account for the explicit purpose of linking with sonos (like an account named "sonos").

**Comment by randomnicode** [comment]
It's not a bug, it's a deliberate security feature.

An anonymous use is not able to browse through music because they shouldn't by definition have any permissions: they're anonymous; they're unverified, unknown, untrusted. If they have access to everything, then there's no point of security. They should only have access to things that are public (and therefore have been explicitly made available to everyone, including anonymous).

Thus, they are able to browse public stuff (like, for instance, if you make your playlist public, they should be able to see it), but have no rights to see non-public stuff.

If you'd like to be able to browse all your non-public music, either use one of your existing accounts or create a new user account in airsonic-advanced for the explicit purpose of linking with sonos (like an account named "sonos").

**Comment by uSlackr** [comment]
Integration works great.  One comment for future readers. Use the IP of the airsonic host in the sonos config.  Using DNS (I have a local DNS) allowed me to add the config, but when I added the service in the sonos app, it failed after login.  Switching to IP fixed this.

**Comment by BigMula11** [comment]
> Integration works great.  One comment for future readers. Use the IP of the airsonic host in the sonos config - as the docs say!  Using DNS (I have a local DNS) allowed me to add the config, but when I added the service in the sonos app, it failed after login.  Switching to IP fixed this.
