### ISSUE TITLE
Cannot find "Artist" page using Android clients

### ISSUE THREAD

**Issue by Forceflow** [airsonic-advanced/airsonic-advanced#375]
## Problem description

Cannot find "Artist" page using Android clients.

### Steps to reproduce

1. Use DSub or Ultrasonic to search for an artist while connected to an airsonic-advanced server
2. Observe how the individual tracks by the artist appear in the search result, but not the Artist overview page (the page with all the albums you have of that artist)

## System information

 * **Airsonic version**: 10.6.0
 * **Operating system**: Ubuntu 20.04 Docker
 * **Java version**: (included in docke rimage)
 * **Proxy server**:  None
 * **Client**: Ultrasonic / Dsub, latest versions from Google Play Store
 * **Language**: Standard / English

## Additional info
I can bring up the following page in Dsub when connected to regular airsonic, but not when I'm connected to airsonic-server. Same music collection.
![Screenshot_20200915-120814](https://user-images.githubusercontent.com/3607063/93197696-3eb75980-f74c-11ea-9ff4-fcf8c81af82b.jpg)

**Comment by randomnicode** [comment]
Hmmm, should this be filed under DSub's github? I'm not sure why a certain UI element disappears

**Comment by Forceflow** [comment]
> 
> 
> Hmmm, should this be filed under DSub's github? I'm not sure why a certain UI element disappears

Yeah, I was thinking about that, but the reason I file it here is because I think it's a difference in implementation between airsonic <-> airsonic-advanced, since I can replicate it in two seperate Android players, which both work fine with the standard airsonic server.

I'm not well-versed in the subsonic API, but is there a concept of an "artist query", or is it all song/file-based?

**Comment by wabkia** [comment]
I am nearly positive this is a bug in airsonic.

try searching in the web gui, you see that the artist is not being populated/read properly somewhere. i can search any of my artists and this happens. this is on a fresh database, because i wasnt able to upgrade from my 10.6.2 vanilla database. 

I wouldnt normally mention this tangential issue but it seems like it might be related in this case.

"Caused by: java.sql.SQLException: No suitable driver found for jdbc:hsqldb:file:/var/airsonic/db/airsonic;hsqldb.tx=mvcc;sql.enforce_size=false;sql.char_literal=false;sql.nulls_first=false;hsqldb.defrag_limit=50;shutdown=true" 

<img width="921" alt="Screen Shot 2020-09-16 at 11 48 58 PM" src="https://user-images.githubusercontent.com/9922669/93430425-81c21b80-f877-11ea-93ba-2985196fbc9a.png">

**Comment by Forceflow** [comment]
@wabkia : Are you claiming this to be a bug in airsonic-advanced or in airsonic? Because my regular vanilla airsonic install I can find the artists like you describe.

**Comment by wabkia** [comment]
@Forceflow this is airsonic-advanced. airsonic is all but dead IMO.

**Comment by Forceflow** [comment]
Yeah, I think we can start to conclude there was a digression / deviation from the subsonic standard when handling artist queries.

I would have no idea where to start looking, though.

**Comment by Forceflow** [comment]
I don't know what I did to remedy it, but I cannot replicate this problem anymore with latest docker image.
