### ISSUE TITLE
description varchar to text type conversion not possible due to emojis

### ISSUE THREAD

**Issue by HolyMacarony** [airsonic-advanced/airsonic-advanced#456]
## Problem description
Please exchange this:
ALTER TABLE airsonic.podcast_episode MODIFY COLUMN description TEXT;

with e.g.:
ALTER TABLE airsonic.podcast_episode MODIFY COLUMN description TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL NULL;

Otherwise all of the podcast descriptions which contain emojis cannot be kept in the database... (almost every single one)

"Incorrect string value: '\xF0\x9F\x99\x88\xF0\x9F...' for column `airsonic`.`podcast_episode`.`description`"

this problem is apparent since commit  23a041f (Merge pull request #444 from randomnicode/podcastdescriptiontext)
### Steps to reproduce

simply launch a current version of the airsonic.war and have some podcast descriptions with emojis in it 😉😱

## System information

 * **Airsonic version**: all from 23a041f  on

**Comment by randomnicode** [comment]
>  ALTER TABLE airsonic.podcast_episode MODIFY COLUMN description TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL NULL;

You haven't specified, but we presume you're using MySQL (or derivatives like MariaDB or HSQL compatibility mode) based on your SQL charset name and collation in the prescribed SQL statement.

Your issue is that your default server-level MySQL charset is set to be something non-utf-based (MySQL 5.7 below have a different default than utf8mb4). This issue is extensively covered in other Airsonic and Airsonic-Advanced tickets (example: https://github.com/airsonic/airsonic/issues/1563), but effectively we deliberately try to not say anything about charsets and collations, and leave that to the db server itself.
When we migrate a column, we are deliberately telling the db server to use whatever the charset it thinks is set by the user. In your case, your default is NOT utf8mb4, so the column ends up being non-utf also.

You should probably set the default server charset to utf8mb4.

Let us know if this is NOT the case.

**Comment by randomnicode** [comment]
Issue is stale, closing, feel free to reopen if this was not the issue
