### ISSUE TITLE
QA: Migration?

### ISSUE THREAD

**Issue by gerroon** [airsonic-advanced/airsonic-advanced#497]
Hi

I would like to try AA and I am wondering if this is compatiple with the current Airsonic Docker install I have. Which docker version shall I use?

This is the mian part of my docker (omitted the volumes)

```
docker run --name airsonic -d \
  --restart=always \
  -e PGID=1000 -e PUID=1000 \
  --group-add audio \
  --device /dev/snd \
  --privileged \
  -v /etc/localtime:/etc/localtime:ro \
  -v /var/run/dbus:/var/run/dbus \
  -v /dev/shm:/dev/shm \
  --net=host \
  -e JAVA_OPTS="-Xmx768m -Dserver.port=8282 -Dserver.contextPath=/airsonic -Dairsonic.contextPath=/airsonic" \
  -p 8282:8282 \
  airsonic/airsonic

```

**Comment by randomnicode** [comment]
Mostly compatible, you'll just need to remap the volumes. See [Docker notes](https://github.com/airsonic-advanced/airsonic-advanced#docker)
And note you don't need to provide all this detail in `JAVA_OPTS` even in your current image
  - contextPath has an env var CONTEXT_PATH
  - port has a env var AIRSONIC_PORT
  - you're overriding the default container port when you are going to rebind it anyway to a host port (instead of overriding it to 8282 and then binding it to host 8282, you can just leave the container port to be the default 4040, and bind it to the host 8282)

```
docker run --name airsonic -d \
  --restart=always \
  -e PGID=1000 -e PUID=1000 \
  --group-add audio \
  --device /dev/snd \
  --privileged \
  -v /etc/localtime:/etc/localtime:ro \
  -v /var/run/dbus:/var/run/dbus \
  -v /dev/shm:/dev/shm \
  --net=host \
  -e JAVA_OPTS="-Xmx768m" \
  -e CONTEXT_PATH="/airsonic"
  -p 8282:4040 \
  -v Your-music:/var/music \
  -v Your-Playlists:/var/playlists \
  -v Your-Podcasts:/var/podcasts \
  -v Your-Airsonic-Db-and-Data:/var/airsonic \
  airsonicadvanced/airsonic-advanced:latest
```
