### ISSUE TITLE
Failed to collect dependencies at o rg.fourthline.cling:cling-core:jar:2.0.1:

### ISSUE THREAD

**Issue by rain0r** [airsonic-advanced/airsonic-advanced#607]
So I just cloned this repo and tried to build it via `mvn -Dmaven.test.skip=true clean package` (like stated in `CONTRIBUTING`) but maven fails trying to load a dependency:

```
[ERROR] Failed to execute goal on project airsonic-main: Could not resolve dependencies for project org.airsonic.player:airsonic-main:war:11.0.0-SNAPSHOT: Failed to collect dependencies at o
rg.fourthline.cling:cling-core:jar:2.0.1: Failed to read artifact descriptor for org.fourthline.cling:cling-core:jar:2.0.1: Could not transfer artifact org.fourthline.cling:cling-core:pom:2.
0.1 from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [4thline-repo (http://4thline.org/m2, default, releases+snapshots)] -> [Help 1]
```

How can I build the current master?

---

Edit: The reasons seems to be that Maven blocks `http` repos. I would suggest to either enable SSL for http://4thline.org/ (via LetsEncrypt for example) oder upload `cling-core` to maven central.

**Comment by randomnicode** [comment]
This was actually addressed in #533 

The root cause is, as you've established, that newer Mavens block http repos.

- SSL for 4thline.org is not an option because it is a third-party repo, we do not have access to nor own the domain.
- If you would like to take over the responsibility for uploading to Maven Central and maintain it, we may be able to switch over
- The alternative is to unblock http access in maven settings. This is done in [this file](https://github.com/airsonic-advanced/airsonic-advanced/blob/master/.mvn/settings.xml) and is used by the CI/CD pipeline here:
https://github.com/airsonic-advanced/airsonic-advanced/blob/aaff900229c98d3641d0ab7f219ede861ec38137/.github/workflows/pr_ci.yml#L33

You would run it similarly: `mvn --settings=/path/to/settings-with-unblocked.xml -DskipTests clean package`

**Comment by rain0r** [comment]
Thanks for the answer!

**Comment by rain0r** [comment]
Closed this issue by accident.

I can upload `cling-core` to Maven Central.

Does it have to be version `2.0.1`? Latest release is `2.1.2`.

**Comment by randomnicode** [comment]
2.1.2 lacks some key classes that we use, thus we continue using 2.0.1

You may upload both (probably should), but we will continue using 2.0.1 for now

There is a long history of upgrading to 2.1.2, finding issues with dlna, then reverting the upgrade back to 2.0.1. We keep forgetting.

https://github.com/airsonic/airsonic/pulls?q=is%3Apr+is%3Aclosed+cling

**Comment by randomnicode** [comment]
` mvn --settings=./.mvn/settings.xml -DskipTests -Dcheckstyle.skip=true clean package ` should compile
