### ISSUE TITLE
Update from 10.6 to 11: integrity constraint violation: unique constraint or  index violation: IDX_ARTIST_NAME

### ISSUE THREAD

**Issue by nRaecheR** [airsonic-advanced/airsonic-advanced#634]
I'm trying to update from Airsonic-Advanced v10.6.0 to v11 (Docker Tag Latest from 25.9.2021). The first start fails with a Java exception during the database migration. Heres the output from the log file:

```
2021-09-25 18:01:15.885  INFO --- o.a.p.u.LegacyHsqlMigrationUtil          : HSQLDB database upgrade needed, from version 1.8.0 to 2.5
2021-09-25 18:01:16.025  INFO --- o.a.p.u.LegacyHsqlMigrationUtil          : HSQLDB database backed up to /var/airsonic/db.backup.20210925180115
2021-09-25 18:01:25.859 ERROR --- h.db.HSQLDB7C1DB075AE.ENGINE             : error in script file line: 368819 org.hsqldb.HsqlException: integrity constraint violation: unique constraint or 
index violation: IDX_ARTIST_NAME
```
The installation was migrated from Airsonic 10.6.0 to Airsonic-Advanced before. This migration has worked as expected.

### Steps to reproduce

1. Have an Airsonic installation that worked for years, update to latest 10.6.0
2. Update to Airsonic-Advanced 10.6.0 (Docker tag : 10)
3. Update to Airsonic-Advanced 11-Snapshot (Docker tag : latest)

## System information

 * **Airsonic version**: *Docker "Latest" version from 25.9.2021*
 * **Operating system**: *Podman 3.20 on Ubuntu 21.04, AMD64*
 * **Java version**: *From Docker "Latest" version from 25.9.2021*
 * **Proxy server**: *NGINX Docker Container, latest*

**Comment by randomnicode** [comment]
Hi, looks like your db may be corrupt. It may have been corrupt all this time and you may not have realized it because your installation didn't access the region of the db that was corrupted.

You have two options:
- Try fixing the DB: You can look at the line 368819 of your backed up db (db.backup.20210925180115/airsonic.script) and see what artist is being inserted again in the db. If you post the db folder/file here, we may be able to take a look
- Start with a clean DB: Delete the db folder and start anew. The media folders will be repopulated after the first scan. You may lose the ratings

**Comment by nRaecheR** [comment]
Thank you for your answer, the line in question is 

```
 368819 INSERT INTO ARTIST VALUES(6533,'The Phantom of the Opera (Original London Cast) ','/musics/Musical/The Phantom of the Opera (Original London Cast) /CD1/folder.jpg',1,'2021-09-25 17:2 368819 3:43.029742000',TRUE,0)
 
``` 
Cleaning the db isn't an option because we'll loose all playlists, stars etc. To backup these manually for all users isn't viable.

**Comment by nRaecheR** [comment]
I've renamed the directory in question, removing the trailing space char, and repeated the migration to 11-snapshot. Now it works. But I think it should work with the old directory name, it's a valid Linux directory name.

**Comment by randomnicode** [comment]
Hmmm, a unique constraint violation implies that you already have a similar artist name in your db. Can you search your db for another instance where `The Phantom of the Opera (Original London Cast) ` was inserted?

Locations with trailing spaces should absolutely work with airsonic-advanced.

**Comment by nRaecheR** [comment]
Yes, there is another entry but without the trailing space: 

```
INSERT INTO ARTIST VALUES(2455,'The Phantom of the Opera (Original London Cast)','/musics/Musical/The Phantom of the Opera (Original London Cast) /CD1/folder.jpg',1,'2021-09-22 11:47:46.000000000',TRUE,0)
INSERT INTO ARTIST VALUES(6533,'The Phantom of the Opera (Original London Cast) ','/musics/Musical/The Phantom of the Opera (Original London Cast) /CD1/folder.jpg',1,'2021-09-22 11:47:46.000000000',TRUE,0)
```

But there is no directory without the space char in the music folder.

**Comment by randomnicode** [comment]
There are 2 issues here.

Context:
---
The music scanner will derive its artist data from two sources, in order (first is more preferential):
 - the ID3 tags of the songs: This trims the value and replaces "\0" (sometimes a invalid character in the tag) with a space.
 - the folder name itself. This is left intact and no trimming is done.

The scanner scans over all files and collects the names of artists for each file in a set in memory.
If an artist has been seen before, the set already has the artist name, and it doesn't need to be written down again.
After all files have been scanned, the scanner commits all of the artists in the set to the DB.
Theoretically, because the in-memory set will only have unique artists, the DB uniqueness constraint will never be triggered.

How it applies in this scenario:
---
*Issue 1: Generation of artist names with and without trailing spaces*
Your scanner presumably goes through the Phantom of the Opera folder and finds two kinds of files:
  - There are some files there that have an ID3 tag for an artist. Those ID3 tags are taken and trimmed and result in a non-trailing whitespace name for an artist.
  - There are other files that either (a) have a trailing "\0" in the ID3 tag for artist, or (b) have no ID3 tags. Either of these scenarios leads to an artist name that has a trailing whitespace (the former replaces the "\0" with a space and the latter uses the folder name that has a trailing whitespace).

Both of the artists are considered unique in the memory set because of the whitespace difference and added to it separately.

*Issue 2: Uniqueness violation in the DB*
Older versions of the HSQLDB (upto 1.8) differentiated between a space at the end and a nonspace at the end.
This is no longer true, and requires a DB collation change. We will add it to the migration connection string. The property is `sql.pad_space` and documented in HSQLDB: https://fossies.org/linux/hsqldb/hsqldb/doc/guide/dbproperties-chapt.html

**Comment by nRaecheR** [comment]
It's true, one of the FLAC files in the directory misses the ARTIST tag in the VORBIS_COMMENT metadata block.
