### ISSUE TITLE
search does not find some albums

### ISSUE THREAD

**Issue by cascooscuro** [airsonic-advanced/airsonic-advanced#644]
## Problem description

It looks that I have issues with search.

I'm using latest release , and have gone through "Full Scan", but some albums don't appear when I search for them.

For example this album folder :

`.../soundtrack/Various Soundtrack Artists/(2011) Drive: Original Motion Picture Soundtrack (LKS 342322)  [FLAC]`

and its tags:
`Input #0, flac, from '01 - Kavinsky & Lovefoxxx - Nightcall.flac':
  Metadata:
    artist          : Kavinsky & Lovefoxxx
    title           : Nightcall
    album           : Drive (Original Motion Picture Soundtrack)
    date            : 2011
    track           : 01
    genre           : Soundtrack`

if I search by "Drive", the album is not included in the results.

The only way I can get it to appear is by searching for the whole name. Either "Drive Original Motion Picture Soundtrack" or "Drive: Original Motion Picture Soundtrack".

Not sure if the colon is messing the parsing logic.

Another example. This album folder:

`.../soundtrack/Various Soundtrack Artists/(2001) Ocean's Eleven [FLAC]`

and its tags:
`Input #0, flac, from '1.17. Hookers.flac':
  Metadata:
    ALBUM           : Ocean's Eleven
    album_artist    : David Holmes
    ARTIST          : David Holmes
    disc            : 1
    GENRE           : Soundtrack
    TITLE           : Hookers
    DISCTOTAL       : 1
    TRACKTOTAL      : 21
    DATE            : 2001
    track           : 17
`

If I search by "Eleven" I get the album. But if I try with "Ocean's" there are no results.

Apart from the "airsonic-advanced" instance I'm running an "airsonic" one, pointing to the same folders. I'm not seeing this search issues with the Airsonic instance.

Thanks for you help!!

## System information

 * **Airsonic version**: (11.0.0-SNAPSHOT.20210908073208)
 * **Operating system**: *Linux Arch*
 * **Java version**: *java 11.0.12, Linux *
 * **Proxy server**: *nginx/1.19.6*

**Comment by randomnicode** [comment]
The search algorithm wasn't touched after the fork between airsonic and airsonic-advanced. So in that sense, it should be the same.

However, we believe it was tweaked soon before the fork. Whether those changes never made it to a stable airsonic release is a different story.

**Comment by robertdecaire** [comment]
I'm also having issues with search. 

For example, I've got some Debussy tracks in various albums. Search only seems to think an album contains Debussy if the path to the album contains Debussy. If I search for "Debussy" it brings up "Debussy" and "Claude Debussy" (since he's listed on various albums as both). But it only lists albums and songs where the artist is "Debussy" and not "Claude Debussy". If I search for "Claude Debussy", I get the same results. If I search for "Claude", I get _some_ albums where he's listed as "Claude Debussy", but not all of them. But it lists the songs where he's credited as "Claude Debussy" right underneath, from albums that aren't in that album list.

It's a real mess. Is there any plan to make search functional?

**Comment by cascooscuro** [comment]
We can close this. Search indeed finds those albums, the issue is that I was hitting the search limit (25)

It would be great if could get all search results

As also described in this issue: https://github.com/airsonic-advanced/airsonic-advanced/issues/748
