### ISSUE TITLE
admin can't see credentials for other users

### ISSUE THREAD

**Issue by beardedfool** [airsonic-advanced/airsonic-advanced#680]
Using docker:latest 11.0.0-SNAPSHOT.20211202100235
I wanted to create a limited user that can't change their own password (connection from volumio)
No admin access 
User NOT allowed to change personal settings and own password

As user without access to settings/ credentials I can't delete my old password
As Admin I can't see other user's credentials so I can't delete old ones. 

So there's no way to revoke credentials/ change password without destroying the user.
Or 
allowing them to change
logging on as them
changing password and deleting old ones
logging on as admin
removing rights

Fair enough if it's a design choice/ too difficult that admin can't see credentials but wanted to check I'm not being stupid here please?

**Comment by randomnicode** [comment]
yup, so far it's a design choice.

No one can see your creds except yourself.

If creds need to be changed, admin can temporarily grant settings access, and then revoke it.

**Comment by courtarro** [comment]
I am trying to set up an Airsonic server behind a reverse proxy which will be used by others who use the DSub client. DSub needs an AES password. Because the reverse proxy is handling authentication before Airsonic even gets the request, I need to set the users' passwords in the reverse proxy and set the same password for them in Airsonic. How do I set an AES credential for the users?

Similarly, it doesn't look like there's a way to change an existing user's password. If I can only add credentials to their accounts, then I can't properly administer the accounts of other users. I need to be able to clear their existing credentials.

**Comment by randomnicode** [comment]
- The type of creds you can add is in the encoder category when you add them on the Credential tab of Settings. default is bcrypt but you may add an aes (encrypted-aes-gcm) cred also
- Instead of changing, you add new creds and delete old ones. that's effectively clearing creds
- Since you know their creds because you're setting them up, you have to log on as them in order to do the above. You can't do it from any other account other than theirs.
- The sequence goes:
  - Log in as them with old password
  - Add new creds with AES encoder
  - Remove old creds (that you used to log in)

That's it.
