### ISSUE TITLE
How many users can airsonic-advanced handle?

### ISSUE THREAD

**Issue by izyspania** [airsonic-advanced/airsonic-advanced#691]
How many users can airsonic-advanced handle? What specs should server have for about 500 users? Im building and android app (subsonic api) with audiobooks for the blind people in my city (city association) so it could have from 100 to 2000-3000 members and i am not sure what server hardware should i have for this many users (im just assuming that sometimes they could be like 500 users at the same time , prob less but to be on the safe side) or if airsonic-advanced is suited for this amount of users. Most of them they will use the android app so the most traffic/usage with be from that. 
There will be like 100k audiobook files, 5-20 files per book. 96kbps to 192kbps, most of them 128 kbps. (i can enable or disable transcoding if thats a big performance hit)
Thanks

**Comment by Abraka** [comment]
500+ users at same time? Forget that with *any*sonic platform. Its good solution for personal music streaming and-or for few family members and friends lets say, but its not a profi distribution-streaming platform for masses. Its true that *sonic platform supports LDAP, wich is something you will need for managing so many user accounts no matter what platform you will use at the end, but even without transcoding wich you dont need with 128kbps, this will not fly.
You would need something like https://funkwhale.audio/ which can scale to your needs and far beyond. 
Server spec...start with 8-16 cores, 32-64GB Ram, x00GB on fast SSD for OS and PostgreSQL and finaly some disk space for yours audiobook library...but with concurent 500+ users forget standard slow 7200rpm HDD and go rather with SSD storage.
And of course good hosting for your server - virtual or hw with appropriate link speed (500+ x 96-192kbps). 
Good luck, hope you have funds for this for long run.

**Comment by izyspania** [comment]
Ill be hosting it on my own server. Im looking into ampache now. thanks for your answer!

**Comment by Abraka** [comment]
Ampache? Huh, well good luck with that :)

**Comment by izyspania** [comment]
Well im not sure if ill go with but ill have to test it, ppl said that it can handle that amount of users as long i have ok hardware on my server.

**Comment by Abraka** [comment]
Well, its not a java, its php+apache+sql so its much more powerfull combo in this case. Not so sure about ampache platform itself in term of management..its simply have ugly, very confusing interface and configuration. In this regard *sonic projects are miles ahead. But if you manage to work around that somehow, you get more power from you hw for sure.

**Comment by randomnicode** [comment]
> Well, its not a java, its php+apache+sql so its much more powerfull combo in this case.

ummm. no. just no.

@izyspania 

there is a distinction between:
- number of users
- number of concurrent users
- amount of media

having 500 or 1000s of users is not an issue for airsonic
similarly having a lot of media is not an issue for airsonic
things start becoming dicey when the server has to bear concurrent load, i.e. 500 users all asking for 500 different streams will cause slightly more stress on the system. if you're asking for 500 transcodes, your bottleneck is your cpu. otherwise, direct streaming from a lot of files will possibly cause hdd read bottlenecks (depending on your hdd). these bottlenecks are on the server side and assume the network bandwidth isn't saturated.

the short answer is no one knows.
perhaps you could benchmark and figure out the bottlenecks for both server programs and document them? we suspect airsonic is going to be more performant in just about every way possible, especially as the caching kicks in.

500 users isn't a lot, and the issue isn't really about the program but about bottlenecks in your hardware system, which you should figure out and engineer solutions for. for instance, if hdd read is a bottleneck, you could shard your media on multiple disks, etc.

**Comment by izyspania** [comment]
Hi and thanks for the info , the idea is that the spike of maybe 500 users (maybe 3-400) can happen maybe 2 3 times a month  , in general im expecting like 20 30 de users at the same time and maybe a max of 100 for an hour per day (at the same time). Im expecting that 90% of them will be using it from an android client (a fork of dsub) and they will preload like 3 -5 tracks in advance.
Most of the mp3s are 128 kbps and 192kbps and they are 15-20mb in size. The connection will be 1gbit up and down. I can remove the transcode (or maybe leave it for the 5% of mp3s that are > 192kbps).

Now my problem is that i have no idea what hardware do i need , like how many cores , how much ram and what kind of storage. Ofc im looking for the cheapest way to do it , i still havent decided if i want to build a server (and use 1gbit connection) or i should buy an VPS. VPS prices seem to explode if i want 1tb+ storage , more than 2 cores or more than 2gb of RAM, but if something like 2 cores , 2gb ram + lets say 256 SSD + 1 or 2tb normal hdd can handle what i need then i might be able to find some VPS for a decent price, for everything higher than that i need to build a server as its much cheaper on the long run. I can probably transcode everything to 96 or 128 kbps from the start and i could save some space and bandwidth (i dont think audiobooks need more than 128 for good quality as its only voice?) .

Second problem is what should i go for , airsonic-advanced or ampache, airsonic seems to scan the files faster and has more out of the box functionality but its harder to customize and i dont know how many connections / burst can handle with a reasonable cpu usage . Ampache has more options and is using apache/NGINX + php but many are useless to me. A member of ampache project to me this "You're really just limited by how much effort, hardware and time you want to throw at it,", still no1 can give me some numbers,, like this CPU (or cores) will be more than enough for that many connections.

**Comment by randomnicode** [comment]
The reason no one has been able to answer for you is because you need to figure these answers out yourself. There are too many variables to consider here for someone to already have the answers. And the best person that knows the variables range is you.
Do a load test on a test server, whatever you have, and see how far you can push it under what circumstances.
No one knows how much ram, cpu or hdd (or ssd) to tell you because no one knows which bit is the bottleneck and you need to increase that part.

Your data storage is directly dependent on how much media you have. No one has this answer except you. How many mp3s do you have? what's the size of your collection? 1tb+ is a lot of hd space if it's not movies. whether you need ssd or hdd is again dependent on your burst requirement, there's a lot of ssds and hdds out there, figure out which random read speed can accommodate your designs.
CPU cores are less important, except when transcoding comes into play, then it's super important. Plus you'll need an additional bit of it obviously for the normal dealing of stuff. RAM may or may not be a factor depending on the collection size (Airsonic-advanced assembles a collection in memory and then commits all of it to the db).

The threadpool for network connections, db connections etc, can all be customized on airsonic also. php is a process-based thing, instead of thread-based, theoretically may require more memory, but without having seen the architecture for ampache, no idea for sure.

**Comment by Abraka** [comment]
I already gave you some numbers for start, but as randomnicode says correctly ..fire up test server, load some GB in library and test connections. Of course we expect that you report some results back here, whatewer they will be.
