### ISSUE TITLE
Install Airsonic Advanced that would enable me to make changes to .jsp files

### ISSUE THREAD

**Issue by angelawong** [airsonic-advanced/airsonic-advanced#719]
When I install using the airsonic.war file, I noticed that I cannot change or customize the jsp files easily.

For Subsonic, all I have to do is _sudo dpkg -i subsonic-x.x.deb_

Not only does it install the application, it allows me to make changes to the .jsp , css and other template files very easily. Is there a similar way of installing airsonic-advanced that enables me to make such changes easily?

Any help or advice would be most appreciated. Thanks so much!

**Comment by randomnicode** [comment]
Hi,

The issue is that instead of compiling at runtime, jsps are precompiled in airsonic-advanced to speed up their loading. The operational plugin at build-time is here:

https://github.com/airsonic-advanced/airsonic-advanced/blob/f52dc461ed1019648a497a2209eea9aff01635c3/airsonic-main/pom.xml#L681-L701

Here is the commit where this happened: https://github.com/airsonic-advanced/airsonic-advanced/commit/e7bd5da6fa437029e64ec4d31adf5dcc3a4ddd87#diff-28acd9f773c93be336c261102dbebed2f36f1bb47f4fc28015cec97c54f00724

You can revert this commit for your own build and see if that helps.

**Comment by randomnicode** [comment]
also you could try running airsonic in development mode and there seems to be code that eliminates the caching issue?

`-Dairsonic.development=true`

**Comment by angelawong** [comment]
Thanks so much @randomnicode. I am unfamiliar with Java and so please forgive my ignorance.

So here is what I tried to do:
1. Extract airsonic.war file to see what is in it:
`jar -xvf airsonic.war`

2. It expanded out to the following files:
browserconfig.xml
favicon.ico
/icons
index.html
index.jsp
/META-INF
/org
/script
/sonos
/style
/WEB-INF

3. Without making any changes, I tried to convert it back to a .war file:
jar -cvf airsonic.war * 

4. After doing this, I can no longer run the airsonic.war file.

What is in the jar commands that corrupted the airsonic.war file?

I was hoping that if this worked, I could make changes to the .jsp file and then compress it back to the airsonic.war.
