### ISSUE TITLE
DBMS Precondition failed: expected mariadb,mysql, got hsqldb

### ISSUE THREAD

**Issue by J-T-W** [airsonic-advanced/airsonic-advanced#788]
## Problem description

Update from 11.0.0-SNAPSHOT.20220124042650 to 11.0.0-SNAPSHOT.20220129204202.  AA fails to start with airsonic.log citing "DBMS Precondition failed: expected mariadb,mysql, got hsqldb"

### Steps to reproduce

Shut down 20220124042650, swap WAR, start 20220129204202

## System information

 * **Airsonic version**: *the version listed on the About page*
n/a 

 * **Operating system**: *the operating system you're running Airsonic on.
Windows 2019

 * **Java version**: *the Java version you are using to run Airsonic.*
 17.0.1

 * **Proxy server**: *if running Airsonic behind a proxy, what server and
   version? Otherwise,* 
None

 * **Client**: *what browser and version you use to access the Airsonic web
   interface, or the name and version of another app you're using.*
Edge Chromium / Google Chrome

 * **Language**: *which langauge/internationalization is in use*
*en-US

## Additional notes

Added Logs
[airsonic.log](https://github.com/airsonic-advanced/airsonic-advanced/files/7998500/airsonic.log)
[airsonic.log](https://github.com/airsonic-advanced/airsonic-advanced/files/7998504/airsonic.log)

**Comment by neo-backwards-one** [comment]
## Problem description
same as op (log is identical), differences in bold+italic:
update from 11.0.0-SNAPSHOT.20220124042650 to **_11.0.0-SNAPSHOT.20220203150207_**


## System information
* **Airsonic version**: _the version listed on the About page_
  n/a

* **Operating system**: _the operating system you're running Airsonic on._
  **_debian Linux 4.19.0-11-amd64_**

* **Java version**: _the Java version you are using to run Airsonic._
  **_11.0.8_**

* **Proxy server**: _if running Airsonic behind a proxy, what server and
  version? Otherwise,_
  None

* **Client**: _what browser and version you use to access the Airsonic web
  interface, or the name and version of another app you're using._
  **_Google Chrome Version 98.0.4758.82 (Official Build) (64-bit)_**

* **Language**: _which langauge/internationalization is in use_
  *en-US

**Comment by randomnicode** [comment]
> AA fails to start with airsonic.log citing "DBMS Precondition failed: expected mariadb,mysql, got hsqldb"

This isn't an error. It's informing you that it's not executing the changeset because you have a different db. It's a normal message (it's supposed to say that if you have hsqldb).

Why do you think it's not starting? If it's taking time to come up, it's likely taking time to convert the DB to the new format, which may occur with big media libraries.

Since, this is the last message in the log, there is an assumption that it's an error. It's likely executing the next changeset, which takes time. Please be patient and let it finish. It'll start emitting more messages when it's done.

**Comment by J-T-W** [comment]
Thank you for your response.  I believed it to be an error as there was no log progressed for around an hour (including no file last modified date change), the server showed nothing listening on the defined port, and you can't connect.  

It did start showing new activity after about that 2 hours, where it then crashed.  Subsequent restarts has it showing the activity in the log attached and then crashing

[airsonic.log](https://github.com/airsonic-advanced/airsonic-advanced/files/8002066/airsonic.log)
.

**Comment by randomnicode** [comment]
mind posting your db?
we're specifically like to look at the album table

**Comment by J-T-W** [comment]
Here ya go -  DB folder as of 11.0.0-SNAPSHOT.20220124042650

[db.zip](https://github.com/airsonic-advanced/airsonic-advanced/files/8004644/db.zip)

**Comment by J-T-W** [comment]
Release 11.0.0-SNAPSHOT.20220204175844 worked great - thanks.
