### ISSUE TITLE
[Question] Is there a roadmap to the next stable version?

### ISSUE THREAD

**Issue by iGormilhit** [airsonic-advanced/airsonic-advanced#841]
## [Question] Is there a roadmap to the next stable version?

I'm running two airsonic server. One runs [airsonic 10.6.2][1] and the other one [airsonic-advanced 10.6.0][2]. Each time I encounter a small bug on the [airsonic-advanced 10.6.0][2], I can see it's already been fixed in the dev branch. But there's no stable 11 version yet.

My question is (and I suspect this has been discussed many times, but I couldn't find where), will it ever be such a stable 11 version in the future? If yes, what is it waiting for?

Please be assured that I'm grateful of the work that took place in both airsonic and airsonic-advanced projects.

[1]: https://github.com/airsonic/airsonic/releases/tag/v10.6.2
[2]: https://github.com/airsonic-advanced/airsonic-advanced/releases/tag/v10.6.0

**Comment by randomnicode** [comment]
This is a fair point.

One of the reasons we branched was precisely because of this issue.

Devs would add to the branch, and the changes would accumulate and build up with no release until someone decided to do a release. Important changes or bug fixes would pile up, and unless you had the ability to compile it yourself, you were reliant on other devs to get a binary with the fix to you.

We decided to skirt the issue by doing a release after every merge. We called it EDGE and the intention was a to keep it as stable as possible. While it didn't fix the issue of a stable release every so often, it did allow the builds to get into the hands of users faster.

By some opinions here, we should have done a stable release for 11.0 before the relative-path change was put in, and moved the development to 11.1-SNAPSHOT. We will probably retroactively do that, and switch all of the development over.

While there is no "roadmap", you are encouraged to be on the EDGE releases, which are (generally) stable enough.

**Comment by iGormilhit** [comment]
@randomnicode Thanks for your answer. So if I get it right, I can install a recent EDGE release and then update *periodically*, which means as I want or "need"?

**Comment by randomnicode** [comment]
Yup

**Comment by iGormilhit** [comment]
Okay, will do, then. :slightly_smiling_face: 

Thanks.
